services:
  postgres:
    build:
      context: ./postgres
      args:
        - DB_LANG=ja_JP
    command: postgres -c log_statement=all
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - default
      - shared

  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_data_file_path=ibdata1:1G
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - default
      - shared

  mysql8:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql8-data:/var/lib/mysql
    ports:
      - '3308:3306'
    networks:
      - default
      - shared

networks:
  shared:
    external: true

volumes:
  postgres-data:
    external: true
  mysql-data:
    external: true
  mysql8-data:
    external: true
